services:
    kms:
        build: .
        container_name: personal-kms
        ports:
            - "3000:3000"
        environment:
            - KMS_PORT=3000
            - KMS_WHITELIST=0.0.0.0/0
            - KEY_STORE_PATH=/data/keys
            - NODE_ENV=development
        volumes:
            - kms-data:/data

    client:
        image: node:20-alpine
        container_name: kms-client
        working_dir: /work
        depends_on:
            - kms
        environment:
            - BASE_URL=http://kms:3000
            - TOKEN=demo-client-token
        volumes:
            - .:/work:rw
        command: >-
            sh -c "echo 'Hello via KMS!' > /work/sample.txt && node /work/client/testE2E.mjs /work/sample.txt /work/cipher.json /work/roundtrip.txt"

volumes:
    kms-data:
